# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upoprigrpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'upoprigrpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10upoprigrpc.proto\x12\x04user\"4\n\x13GetUsernamesRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x05\x12\x10\n\x08uniqueid\x18\x02 \x01(\t\":\n\x11GetStrankaRequest\x12\x13\n\x0bIDUporabnik\x18\x01 \x01(\x05\x12\x10\n\x08uniqueid\x18\x02 \x01(\t\"9\n\x18GetIzbraneStrankeRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x05\x12\x10\n\x08uniqueid\x18\x02 \x01(\t\"7\n\x08Username\x12\x13\n\x0bIDUporabnik\x18\x01 \x01(\x05\x12\x16\n\x0eUporabniskoIme\x18\x02 \x01(\t\"6\n\x11UsernamesResponse\x12!\n\tusernames\x18\x01 \x03(\x0b\x32\x0e.user.Username\"\x8f\x01\n\x0fStrankaResponse\x12\x11\n\tIDStranka\x18\x01 \x01(\x05\x12\x0b\n\x03Ime\x18\x02 \x01(\t\x12\x0f\n\x07Priimek\x18\x03 \x01(\t\x12\r\n\x05\x45mail\x18\x04 \x01(\t\x12\x0f\n\x07Telefon\x18\x05 \x01(\t\x12\x16\n\x0e\x44\x61vcnaStevilka\x18\x06 \x01(\t\x12\x13\n\x0bIDUporabnik\x18\x07 \x01(\x05\"r\n\x07Stranka\x12\x11\n\tIDStranka\x18\x01 \x01(\x05\x12\x0b\n\x03Ime\x18\x02 \x01(\t\x12\x0f\n\x07Priimek\x18\x03 \x01(\t\x12\x0f\n\x07Telefon\x18\x04 \x01(\t\x12\r\n\x05\x45mail\x18\x05 \x01(\t\x12\x16\n\x0e\x44\x61vcnaStevilka\x18\x06 \x01(\t\"8\n\x16IzbraneStrankeResponse\x12\x1e\n\x07stranke\x18\x01 \x03(\x0b\x32\r.user.Stranka2\xd9\x01\n\x0bUserService\x12?\n\tUsernames\x12\x19.user.GetUsernamesRequest\x1a\x17.user.UsernamesResponse\x12\x39\n\x07Stranka\x12\x17.user.GetStrankaRequest\x1a\x15.user.StrankaResponse\x12N\n\x0eIzbraneStranke\x12\x1e.user.GetIzbraneStrankeRequest\x1a\x1c.user.IzbraneStrankeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upoprigrpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERNAMESREQUEST']._serialized_start=26
  _globals['_GETUSERNAMESREQUEST']._serialized_end=78
  _globals['_GETSTRANKAREQUEST']._serialized_start=80
  _globals['_GETSTRANKAREQUEST']._serialized_end=138
  _globals['_GETIZBRANESTRANKEREQUEST']._serialized_start=140
  _globals['_GETIZBRANESTRANKEREQUEST']._serialized_end=197
  _globals['_USERNAME']._serialized_start=199
  _globals['_USERNAME']._serialized_end=254
  _globals['_USERNAMESRESPONSE']._serialized_start=256
  _globals['_USERNAMESRESPONSE']._serialized_end=310
  _globals['_STRANKARESPONSE']._serialized_start=313
  _globals['_STRANKARESPONSE']._serialized_end=456
  _globals['_STRANKA']._serialized_start=458
  _globals['_STRANKA']._serialized_end=572
  _globals['_IZBRANESTRANKERESPONSE']._serialized_start=574
  _globals['_IZBRANESTRANKERESPONSE']._serialized_end=630
  _globals['_USERSERVICE']._serialized_start=633
  _globals['_USERSERVICE']._serialized_end=850
# @@protoc_insertion_point(module_scope)
